# Generated by Django 5.0.6 on 2024-06-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='cat_fk',
            new_name='cat',
        ),
        migrations.AlterField(
            model_name='person',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
